'use strict';
const express=require('express');const {QueryTypes}=require('sequelize');const sequelize=require('../config/database');const auth=require('../middleware/auth');const {validateCase,transition}=require('../domain/caseWorkflow');const router=express.Router();router.use(auth);
async function rows(sql,replacements,transaction){return sequelize.query(sql,{replacements,transaction,type:QueryTypes.SELECT});}
async function member(tenantId,userId,transaction){if(!tenantId){const e=new Error('x-tenant-id is required');e.status=400;throw e;}const q=await rows('SELECT role FROM cemetery_tenant_memberships WHERE tenant_id=:tenantId AND user_id=:userId AND active=true',{tenantId,userId},transaction);if(!q[0]){const e=new Error('tenant access denied');e.status=403;throw e;}return q[0].role;}const h=f=>async(req,res)=>{try{await f(req,res);}catch(e){res.status(e.status||(e.name==='SequelizeUniqueConstraintError'?409:400)).json({error:e.message});}};
router.get('/',h(async(req,res)=>{const tenantId=req.header('x-tenant-id');await member(tenantId,req.user.id);const q=await rows('SELECT id,state,version,case_data,created_at,updated_at FROM governed_deathcare_cases WHERE tenant_id=:tenantId ORDER BY updated_at DESC LIMIT 100',{tenantId});res.json({cases:q});}));
router.post('/',h(async(req,res)=>{const tenantId=req.header('x-tenant-id'),key=req.header('idempotency-key');if(!key)throw new Error('idempotency-key is required');const data=validateCase(req.body);const result=await sequelize.transaction(async transaction=>{await member(tenantId,req.user.id,transaction);const q=await rows(`INSERT INTO governed_deathcare_cases(tenant_id,case_number,state,case_data,idempotency_key,created_by) VALUES(:tenantId,:caseNumber,'intake',CAST(:data AS jsonb),:key,:userId) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,{tenantId,caseNumber:data.caseNumber,data:JSON.stringify(data),key,userId:req.user.id},transaction);await sequelize.query(`INSERT INTO deathcare_events(tenant_id,case_id,actor_id,event_type,payload) VALUES(:tenantId,:caseId,:userId,'created',CAST(:payload AS jsonb)) ON CONFLICT DO NOTHING`,{replacements:{tenantId,caseId:q[0].id,userId:req.user.id,payload:JSON.stringify({idempotencyKey:key})},transaction});return q[0];});res.status(201).json(result);}));
router.post('/:id/transition',h(async(req,res)=>{const tenantId=req.header('x-tenant-id');const result=await sequelize.transaction(async transaction=>{const role=await member(tenantId,req.user.id,transaction);const q=await rows('SELECT * FROM governed_deathcare_cases WHERE id=:id AND tenant_id=:tenantId FOR UPDATE',{id:req.params.id,tenantId},transaction);if(!q[0]){const e=new Error('case not found');e.status=404;throw e;}const row=q[0];if(Number(req.body.version)!==row.version){const e=new Error('version conflict');e.status=409;throw e;}const next=transition(row.state,req.body.state,role,row.case_data,req.body.note);const updated=await rows('UPDATE governed_deathcare_cases SET state=:next,version=version+1,updated_at=NOW() WHERE id=:id RETURNING *',{next,id:row.id},transaction);await sequelize.query(`INSERT INTO deathcare_events(tenant_id,case_id,actor_id,event_type,payload) VALUES(:tenantId,:id,:userId,'transition',CAST(:payload AS jsonb))`,{replacements:{tenantId,id:row.id,userId:req.user.id,payload:JSON.stringify({from:row.state,to:next,note:req.body.note||null})},transaction});return updated[0];});res.json(result);}));
router.post('/:id/provider-requests',h(async(req,res)=>{const tenantId=req.header('x-tenant-id'),role=await member(tenantId,req.user.id);if(!['manager','integration_operator','admin'].includes(role)){const e=new Error('integration role required');e.status=403;throw e;}if(!['vital_records','mapping','inventory','payment','esignature','publishing','accounting'].includes(req.body.provider))throw new Error('unsupported provider');const q=await rows(`INSERT INTO deathcare_outbox(tenant_id,case_id,provider,payload,status,requested_by) VALUES(:tenantId,:caseId,:provider,CAST(:payload AS jsonb),'pending',:userId) RETURNING *`,{tenantId,caseId:req.params.id,provider:req.body.provider,payload:JSON.stringify(req.body.payload||{}),userId:req.user.id});res.status(202).json(q[0]);}));
module.exports=router;
