const bcrypt = require('bcryptjs');
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const {
  sequelize, Plot, BurialRecord, Deed, IntermentSchedule, PreNeedContract,
  MonumentOrder, PerpetualCareFund, GroundsMaintenance, FlowerPlacement,
  CeremonySchedule, Vendor, ComplianceRecord, MemorialEvent, GenealogyRecord,
  PaymentPlan, CremationNiche, VeteranRecord, DeedTransfer, User
} = require('../models');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('✓ Database synced');

    // Users
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await User.bulkCreate([
      { email: 'admin@cemetery.com', password: hashedPassword, first_name: 'John', last_name: 'Administrator', role: 'admin' },
      { email: 'manager@cemetery.com', password: hashedPassword, first_name: 'Sarah', last_name: 'Manager', role: 'manager' }
    ]);
    console.log('✓ Users seeded');

    // 1. Plots (20 records)
    const plots = await Plot.bulkCreate([
      { section: 'A', row: '1', plot_number: 'A-1-001', plot_type: 'single', status: 'occupied', price: 2500.00, size_sqft: 40, gps_lat: 40.7128, gps_lng: -74.0060 },
      { section: 'A', row: '1', plot_number: 'A-1-002', plot_type: 'single', status: 'occupied', price: 2500.00, size_sqft: 40, gps_lat: 40.7129, gps_lng: -74.0061 },
      { section: 'A', row: '2', plot_number: 'A-2-001', plot_type: 'double', status: 'sold', price: 4500.00, size_sqft: 80, gps_lat: 40.7130, gps_lng: -74.0062 },
      { section: 'A', row: '2', plot_number: 'A-2-002', plot_type: 'single', status: 'available', price: 2800.00, size_sqft: 40, gps_lat: 40.7131, gps_lng: -74.0063 },
      { section: 'B', row: '1', plot_number: 'B-1-001', plot_type: 'family', status: 'occupied', price: 8500.00, size_sqft: 160, gps_lat: 40.7132, gps_lng: -74.0064 },
      { section: 'B', row: '1', plot_number: 'B-1-002', plot_type: 'single', status: 'available', price: 2600.00, size_sqft: 40, gps_lat: 40.7133, gps_lng: -74.0065 },
      { section: 'B', row: '2', plot_number: 'B-2-001', plot_type: 'double', status: 'reserved', price: 4800.00, size_sqft: 80, gps_lat: 40.7134, gps_lng: -74.0066 },
      { section: 'C', row: '1', plot_number: 'C-1-001', plot_type: 'single', status: 'occupied', price: 3000.00, size_sqft: 40, gps_lat: 40.7135, gps_lng: -74.0067 },
      { section: 'C', row: '1', plot_number: 'C-1-002', plot_type: 'cremation', status: 'available', price: 1500.00, size_sqft: 16, gps_lat: 40.7136, gps_lng: -74.0068 },
      { section: 'C', row: '2', plot_number: 'C-2-001', plot_type: 'mausoleum', status: 'sold', price: 15000.00, size_sqft: 100, gps_lat: 40.7137, gps_lng: -74.0069 },
      { section: 'D', row: '1', plot_number: 'D-1-001', plot_type: 'single', status: 'available', price: 2200.00, size_sqft: 40, gps_lat: 40.7138, gps_lng: -74.0070 },
      { section: 'D', row: '1', plot_number: 'D-1-002', plot_type: 'columbarium', status: 'available', price: 1200.00, size_sqft: 4, gps_lat: 40.7139, gps_lng: -74.0071 },
      { section: 'D', row: '2', plot_number: 'D-2-001', plot_type: 'single', status: 'occupied', price: 2400.00, size_sqft: 40, gps_lat: 40.7140, gps_lng: -74.0072 },
      { section: 'E', row: '1', plot_number: 'E-1-001', plot_type: 'family', status: 'sold', price: 9000.00, size_sqft: 200, gps_lat: 40.7141, gps_lng: -74.0073 },
      { section: 'E', row: '1', plot_number: 'E-1-002', plot_type: 'single', status: 'available', price: 2700.00, size_sqft: 40, gps_lat: 40.7142, gps_lng: -74.0074 },
      { section: 'V', row: '1', plot_number: 'V-1-001', plot_type: 'single', status: 'occupied', price: 0, size_sqft: 40, gps_lat: 40.7143, gps_lng: -74.0075, notes: 'Veteran Section' },
      { section: 'V', row: '1', plot_number: 'V-1-002', plot_type: 'single', status: 'occupied', price: 0, size_sqft: 40, gps_lat: 40.7144, gps_lng: -74.0076, notes: 'Veteran Section' },
      { section: 'V', row: '2', plot_number: 'V-2-001', plot_type: 'single', status: 'available', price: 0, size_sqft: 40, gps_lat: 40.7145, gps_lng: -74.0077, notes: 'Veteran Section' },
      { section: 'F', row: '1', plot_number: 'F-1-001', plot_type: 'single', status: 'available', price: 3200.00, size_sqft: 40, gps_lat: 40.7146, gps_lng: -74.0078 },
      { section: 'F', row: '1', plot_number: 'F-1-002', plot_type: 'double', status: 'available', price: 5500.00, size_sqft: 80, gps_lat: 40.7147, gps_lng: -74.0079 }
    ]);
    console.log('✓ Plots seeded (20)');

    // 2. Burial Records (15 records)
    await BurialRecord.bulkCreate([
      { deceased_first_name: 'Robert', deceased_last_name: 'Johnson', date_of_birth: '1935-03-15', date_of_death: '2024-01-10', date_of_burial: '2024-01-15', plot_id: 1, funeral_home: 'Peaceful Rest Funeral Home', obituary: 'Robert was a beloved father and grandfather who served in the Navy.', veteran: true, veteran_branch: 'Navy', next_of_kin: 'Mary Johnson', next_of_kin_phone: '555-0101' },
      { deceased_first_name: 'Eleanor', deceased_last_name: 'Williams', date_of_birth: '1942-07-22', date_of_death: '2024-02-05', date_of_burial: '2024-02-09', plot_id: 2, funeral_home: 'Serenity Gardens', obituary: 'Eleanor was a retired teacher who touched many lives.', veteran: false, next_of_kin: 'Thomas Williams', next_of_kin_phone: '555-0102' },
      { deceased_first_name: 'James', deceased_last_name: 'Martinez', date_of_birth: '1950-11-30', date_of_death: '2024-03-18', date_of_burial: '2024-03-22', plot_id: 5, funeral_home: 'Heritage Memorial', obituary: 'James was a community leader and business owner.', veteran: false, next_of_kin: 'Rosa Martinez', next_of_kin_phone: '555-0103' },
      { deceased_first_name: 'Dorothy', deceased_last_name: 'Chen', date_of_birth: '1938-05-14', date_of_death: '2024-04-02', date_of_burial: '2024-04-06', plot_id: 8, funeral_home: 'Eternal Peace', obituary: 'Dorothy was an artist and philanthropist.', veteran: false, next_of_kin: 'Michael Chen', next_of_kin_phone: '555-0104' },
      { deceased_first_name: 'William', deceased_last_name: 'Thompson', date_of_birth: '1930-09-08', date_of_death: '2024-05-15', date_of_burial: '2024-05-19', plot_id: 13, funeral_home: 'Peaceful Rest Funeral Home', obituary: 'William was a WWII veteran and Purple Heart recipient.', veteran: true, veteran_branch: 'Army', next_of_kin: 'Susan Thompson', next_of_kin_phone: '555-0105' },
      { deceased_first_name: 'Margaret', deceased_last_name: 'O\'Brien', date_of_birth: '1945-12-25', date_of_death: '2024-06-01', date_of_burial: '2024-06-05', plot_id: 16, funeral_home: 'Heritage Memorial', obituary: 'Margaret was a nurse who dedicated her life to caring for others.', veteran: true, veteran_branch: 'Army', next_of_kin: 'Patrick O\'Brien', next_of_kin_phone: '555-0106' },
      { deceased_first_name: 'George', deceased_last_name: 'Anderson', date_of_birth: '1948-02-17', date_of_death: '2024-07-12', date_of_burial: '2024-07-16', plot_id: 17, funeral_home: 'Serenity Gardens', obituary: 'George was a retired firefighter and devoted husband.', veteran: true, veteran_branch: 'Marines', next_of_kin: 'Linda Anderson', next_of_kin_phone: '555-0107' },
      { deceased_first_name: 'Patricia', deceased_last_name: 'Davis', date_of_birth: '1955-08-03', date_of_death: '2024-08-20', date_of_burial: '2024-08-24', plot_id: 3, funeral_home: 'Eternal Peace', obituary: 'Patricia was a musician and choir director.', veteran: false, next_of_kin: 'John Davis', next_of_kin_phone: '555-0108' },
      { deceased_first_name: 'Richard', deceased_last_name: 'Wilson', date_of_birth: '1940-04-11', date_of_death: '2024-09-05', date_of_burial: '2024-09-09', plot_id: 3, funeral_home: 'Peaceful Rest Funeral Home', obituary: 'Richard was an engineer who built bridges across the state.', veteran: false, next_of_kin: 'Karen Wilson', next_of_kin_phone: '555-0109' },
      { deceased_first_name: 'Helen', deceased_last_name: 'Taylor', date_of_birth: '1933-01-20', date_of_death: '2024-10-10', date_of_burial: '2024-10-14', plot_id: 5, funeral_home: 'Heritage Memorial', obituary: 'Helen was a librarian who loved literature and community.', veteran: false, next_of_kin: 'Robert Taylor', next_of_kin_phone: '555-0110' },
      { deceased_first_name: 'Charles', deceased_last_name: 'Brown', date_of_birth: '1937-06-28', date_of_death: '2024-11-01', date_of_burial: '2024-11-05', plot_id: 10, funeral_home: 'Serenity Gardens', obituary: 'Charles was a farmer who loved the land.', veteran: true, veteran_branch: 'Air Force', next_of_kin: 'Nancy Brown', next_of_kin_phone: '555-0111' },
      { deceased_first_name: 'Barbara', deceased_last_name: 'Garcia', date_of_birth: '1960-10-05', date_of_death: '2024-11-20', date_of_burial: '2024-11-24', plot_id: 14, funeral_home: 'Eternal Peace', obituary: 'Barbara was a doctor who served underserved communities.', veteran: false, next_of_kin: 'Carlos Garcia', next_of_kin_phone: '555-0112' },
      { deceased_first_name: 'Thomas', deceased_last_name: 'White', date_of_birth: '1952-03-09', date_of_death: '2024-12-01', date_of_burial: '2024-12-05', plot_id: 5, funeral_home: 'Peaceful Rest Funeral Home', obituary: 'Thomas was a professor of history at the state university.', veteran: false, next_of_kin: 'Jennifer White', next_of_kin_phone: '555-0113' },
      { deceased_first_name: 'Ruth', deceased_last_name: 'Jackson', date_of_birth: '1929-11-15', date_of_death: '2025-01-08', date_of_burial: '2025-01-12', plot_id: 14, funeral_home: 'Heritage Memorial', obituary: 'Ruth was the oldest member of First Baptist Church.', veteran: false, next_of_kin: 'David Jackson', next_of_kin_phone: '555-0114' },
      { deceased_first_name: 'Frank', deceased_last_name: 'Miller', date_of_birth: '1946-07-04', date_of_death: '2025-02-14', date_of_burial: '2025-02-18', plot_id: 5, funeral_home: 'Serenity Gardens', obituary: 'Frank was a Vietnam veteran and community volunteer.', veteran: true, veteran_branch: 'Army', next_of_kin: 'Sharon Miller', next_of_kin_phone: '555-0115' }
    ]);
    console.log('✓ Burial Records seeded (15)');

    // 3. Deeds (15 records)
    await Deed.bulkCreate([
      { deed_number: 'D-2024-001', owner_first_name: 'Mary', owner_last_name: 'Johnson', owner_email: 'mary.j@email.com', owner_phone: '555-0201', owner_address: '123 Oak St, Springfield', plot_id: 1, purchase_date: '2020-05-15', purchase_price: 2500, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-002', owner_first_name: 'Thomas', owner_last_name: 'Williams', owner_email: 'tom.w@email.com', owner_phone: '555-0202', owner_address: '456 Elm Ave, Springfield', plot_id: 2, purchase_date: '2021-03-20', purchase_price: 2500, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-003', owner_first_name: 'Rosa', owner_last_name: 'Martinez', owner_email: 'rosa.m@email.com', owner_phone: '555-0203', owner_address: '789 Pine Rd, Springfield', plot_id: 3, purchase_date: '2019-08-10', purchase_price: 4200, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-004', owner_first_name: 'Michael', owner_last_name: 'Chen', owner_email: 'mike.c@email.com', owner_phone: '555-0204', owner_address: '321 Maple Dr, Springfield', plot_id: 8, purchase_date: '2022-01-05', purchase_price: 3000, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-005', owner_first_name: 'Rosa', owner_last_name: 'Martinez', owner_email: 'rosa.m@email.com', owner_phone: '555-0203', owner_address: '789 Pine Rd, Springfield', plot_id: 5, purchase_date: '2018-11-15', purchase_price: 8000, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-006', owner_first_name: 'David', owner_last_name: 'Lee', owner_email: 'david.l@email.com', owner_phone: '555-0205', owner_address: '654 Cedar Ln, Springfield', plot_id: 7, purchase_date: '2023-06-01', purchase_price: 4800, deed_type: 'pre-need', status: 'active' },
      { deed_number: 'D-2024-007', owner_first_name: 'Susan', owner_last_name: 'Thompson', owner_email: 'sue.t@email.com', owner_phone: '555-0206', owner_address: '987 Birch Way, Springfield', plot_id: 13, purchase_date: '2020-12-20', purchase_price: 2400, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-008', owner_first_name: 'Patrick', owner_last_name: 'O\'Brien', owner_email: 'pat.ob@email.com', owner_phone: '555-0207', owner_address: '147 Walnut St, Springfield', plot_id: 16, purchase_date: '2021-07-15', purchase_price: 0, deed_type: 'perpetual', status: 'active', notes: 'VA provided' },
      { deed_number: 'D-2024-009', owner_first_name: 'Linda', owner_last_name: 'Anderson', owner_email: 'linda.a@email.com', owner_phone: '555-0208', owner_address: '258 Spruce Ave, Springfield', plot_id: 17, purchase_date: '2022-04-10', purchase_price: 0, deed_type: 'perpetual', status: 'active', notes: 'VA provided' },
      { deed_number: 'D-2024-010', owner_first_name: 'Nancy', owner_last_name: 'Brown', owner_email: 'nancy.b@email.com', owner_phone: '555-0209', owner_address: '369 Ash Ct, Springfield', plot_id: 10, purchase_date: '2019-02-28', purchase_price: 15000, deed_type: 'perpetual', status: 'active' },
      { deed_number: 'D-2024-011', owner_first_name: 'Carlos', owner_last_name: 'Garcia', owner_email: 'carlos.g@email.com', owner_phone: '555-0210', owner_address: '741 Poplar St, Springfield', plot_id: 14, purchase_date: '2023-09-15', purchase_price: 9000, deed_type: 'at-need', status: 'active' },
      { deed_number: 'D-2024-012', owner_first_name: 'Jennifer', owner_last_name: 'White', owner_email: 'jen.w@email.com', owner_phone: '555-0211', owner_address: '852 Willow Rd, Springfield', plot_id: 4, purchase_date: '2024-01-10', purchase_price: 2800, deed_type: 'pre-need', status: 'active' },
      { deed_number: 'D-2024-013', owner_first_name: 'Robert', owner_last_name: 'Taylor', owner_email: 'rob.t@email.com', owner_phone: '555-0212', owner_address: '963 Hickory Ln, Springfield', plot_id: 11, purchase_date: '2024-02-01', purchase_price: 2200, deed_type: 'pre-need', status: 'active' },
      { deed_number: 'D-2024-014', owner_first_name: 'Sharon', owner_last_name: 'Miller', owner_email: 'sharon.m@email.com', owner_phone: '555-0213', owner_address: '174 Chestnut Dr, Springfield', plot_id: 15, purchase_date: '2023-11-20', purchase_price: 2700, deed_type: 'pre-need', status: 'active' },
      { deed_number: 'D-2024-015', owner_first_name: 'Karen', owner_last_name: 'Wilson', owner_email: 'karen.w@email.com', owner_phone: '555-0214', owner_address: '285 Sycamore Blvd, Springfield', plot_id: 19, purchase_date: '2024-03-05', purchase_price: 3200, deed_type: 'at-need', status: 'active' }
    ]);
    console.log('✓ Deeds seeded (15)');

    // 4. Interment Schedules (15 records)
    await IntermentSchedule.bulkCreate([
      { deceased_name: 'Robert Johnson', scheduled_date: '2024-01-15', scheduled_time: '10:00', plot_id: 1, interment_type: 'burial', funeral_home: 'Peaceful Rest', funeral_director: 'James Moore', officiant: 'Rev. Smith', expected_attendees: 75, status: 'completed' },
      { deceased_name: 'Eleanor Williams', scheduled_date: '2024-02-09', scheduled_time: '14:00', plot_id: 2, interment_type: 'burial', funeral_home: 'Serenity Gardens', funeral_director: 'Lisa Park', officiant: 'Rev. Johnson', expected_attendees: 100, status: 'completed' },
      { deceased_name: 'James Martinez', scheduled_date: '2024-03-22', scheduled_time: '11:00', plot_id: 5, interment_type: 'burial', funeral_home: 'Heritage Memorial', funeral_director: 'Mark Davis', officiant: 'Father Rodriguez', expected_attendees: 120, status: 'completed' },
      { deceased_name: 'Dorothy Chen', scheduled_date: '2024-04-06', scheduled_time: '09:30', plot_id: 8, interment_type: 'burial', funeral_home: 'Eternal Peace', funeral_director: 'Amy Wong', officiant: 'Rev. Lee', expected_attendees: 50, status: 'completed' },
      { deceased_name: 'William Thompson', scheduled_date: '2024-05-19', scheduled_time: '13:00', plot_id: 13, interment_type: 'burial', funeral_home: 'Peaceful Rest', funeral_director: 'James Moore', officiant: 'Military Chaplain', expected_attendees: 200, status: 'completed', special_requests: 'Full military honors' },
      { deceased_name: 'Margaret O\'Brien', scheduled_date: '2024-06-05', scheduled_time: '10:30', plot_id: 16, interment_type: 'burial', funeral_home: 'Heritage Memorial', funeral_director: 'Mark Davis', officiant: 'Father Murphy', expected_attendees: 80, status: 'completed' },
      { deceased_name: 'George Anderson', scheduled_date: '2024-07-16', scheduled_time: '15:00', plot_id: 17, interment_type: 'burial', funeral_home: 'Serenity Gardens', funeral_director: 'Lisa Park', officiant: 'Rev. Clark', expected_attendees: 150, status: 'completed' },
      { deceased_name: 'John Smith', scheduled_date: '2026-04-10', scheduled_time: '10:00', plot_id: 4, interment_type: 'burial', funeral_home: 'Peaceful Rest', funeral_director: 'James Moore', officiant: 'Rev. Smith', expected_attendees: 60, status: 'scheduled' },
      { deceased_name: 'Anna Kowalski', scheduled_date: '2026-04-12', scheduled_time: '14:00', plot_id: 9, interment_type: 'cremation', funeral_home: 'Eternal Peace', funeral_director: 'Amy Wong', officiant: 'Rev. Brown', expected_attendees: 30, status: 'scheduled' },
      { deceased_name: 'Samuel Green', scheduled_date: '2026-04-15', scheduled_time: '11:30', plot_id: 11, interment_type: 'burial', funeral_home: 'Heritage Memorial', funeral_director: 'Mark Davis', officiant: 'Rabbi Cohen', expected_attendees: 90, status: 'scheduled' },
      { deceased_name: 'Elizabeth King', scheduled_date: '2026-04-18', scheduled_time: '09:00', plot_id: 6, interment_type: 'burial', funeral_home: 'Serenity Gardens', funeral_director: 'Lisa Park', officiant: 'Rev. Williams', expected_attendees: 70, status: 'scheduled' },
      { deceased_name: 'David Foster', scheduled_date: '2026-04-20', scheduled_time: '13:30', plot_id: 12, interment_type: 'inurnment', funeral_home: 'Peaceful Rest', funeral_director: 'James Moore', officiant: 'Rev. Adams', expected_attendees: 25, status: 'scheduled' },
      { deceased_name: 'Maria Gonzalez', scheduled_date: '2026-04-25', scheduled_time: '10:00', plot_id: 15, interment_type: 'burial', funeral_home: 'Eternal Peace', funeral_director: 'Amy Wong', officiant: 'Father Hernandez', expected_attendees: 110, status: 'scheduled' },
      { deceased_name: 'Henry Wright', scheduled_date: '2026-05-01', scheduled_time: '14:30', plot_id: 18, interment_type: 'burial', funeral_home: 'Heritage Memorial', funeral_director: 'Mark Davis', officiant: 'Military Chaplain', expected_attendees: 180, status: 'scheduled', special_requests: 'Full military honors' },
      { deceased_name: 'Jane Cooper', scheduled_date: '2026-05-05', scheduled_time: '11:00', plot_id: 20, interment_type: 'burial', funeral_home: 'Serenity Gardens', funeral_director: 'Lisa Park', officiant: 'Rev. Thomas', expected_attendees: 45, status: 'scheduled' }
    ]);
    console.log('✓ Interment Schedules seeded (15)');

    // 5. Pre-Need Contracts (15 records)
    await PreNeedContract.bulkCreate([
      { contract_number: 'PN-2024-001', client_first_name: 'David', client_last_name: 'Lee', client_email: 'david.l@email.com', client_phone: '555-0301', client_dob: '1960-05-20', plot_id: 7, contract_date: '2023-06-01', total_amount: 6500, amount_paid: 3250, payment_plan: 'monthly', services_included: 'Plot, burial service, marker', status: 'active' },
      { contract_number: 'PN-2024-002', client_first_name: 'Jennifer', client_last_name: 'White', client_email: 'jen.w@email.com', client_phone: '555-0302', client_dob: '1955-09-12', plot_id: 4, contract_date: '2024-01-10', total_amount: 4500, amount_paid: 1500, payment_plan: 'quarterly', services_included: 'Plot, cremation, niche', status: 'active' },
      { contract_number: 'PN-2024-003', client_first_name: 'Robert', client_last_name: 'Taylor', client_email: 'rob.t@email.com', client_phone: '555-0303', client_dob: '1958-03-08', plot_id: 11, contract_date: '2024-02-01', total_amount: 3800, amount_paid: 950, payment_plan: 'monthly', services_included: 'Plot, basic burial', status: 'active' },
      { contract_number: 'PN-2024-004', client_first_name: 'Sharon', client_last_name: 'Miller', client_email: 'sharon.m@email.com', client_phone: '555-0304', client_dob: '1962-11-25', plot_id: 15, contract_date: '2023-11-20', total_amount: 5200, amount_paid: 2600, payment_plan: 'monthly', services_included: 'Plot, burial, headstone', status: 'active' },
      { contract_number: 'PN-2024-005', client_first_name: 'Karen', client_last_name: 'Wilson', client_email: 'karen.w@email.com', client_phone: '555-0305', client_dob: '1970-07-14', plot_id: 19, contract_date: '2024-03-05', total_amount: 5800, amount_paid: 1450, payment_plan: 'quarterly', services_included: 'Plot, burial, monument', status: 'active' },
      { contract_number: 'PN-2024-006', client_first_name: 'Paul', client_last_name: 'Adams', client_email: 'paul.a@email.com', client_phone: '555-0306', client_dob: '1965-01-30', plot_id: 6, contract_date: '2023-04-15', total_amount: 4200, amount_paid: 4200, payment_plan: 'full', services_included: 'Plot, burial service', status: 'active' },
      { contract_number: 'PN-2024-007', client_first_name: 'Lisa', client_last_name: 'Rogers', client_email: 'lisa.r@email.com', client_phone: '555-0307', client_dob: '1972-08-19', contract_date: '2024-05-10', total_amount: 3500, amount_paid: 875, payment_plan: 'monthly', services_included: 'Cremation, niche, service', status: 'active' },
      { contract_number: 'PN-2024-008', client_first_name: 'Steven', client_last_name: 'Clark', client_email: 'steve.c@email.com', client_phone: '555-0308', client_dob: '1948-12-03', contract_date: '2022-09-01', total_amount: 7200, amount_paid: 5400, payment_plan: 'monthly', services_included: 'Double plot, burial, monuments', status: 'active' },
      { contract_number: 'PN-2024-009', client_first_name: 'Angela', client_last_name: 'Hill', client_email: 'angela.h@email.com', client_phone: '555-0309', client_dob: '1975-04-22', contract_date: '2024-06-01', total_amount: 3200, amount_paid: 800, payment_plan: 'quarterly', services_included: 'Plot, basic burial', status: 'active' },
      { contract_number: 'PN-2024-010', client_first_name: 'Mark', client_last_name: 'Young', client_email: 'mark.y@email.com', client_phone: '555-0310', client_dob: '1953-06-17', contract_date: '2023-01-20', total_amount: 5500, amount_paid: 5500, payment_plan: 'full', services_included: 'Plot, burial, headstone, perpetual care', status: 'active' },
      { contract_number: 'PN-2024-011', client_first_name: 'Dorothy', client_last_name: 'Scott', client_email: 'dorothy.s@email.com', client_phone: '555-0311', client_dob: '1968-02-14', contract_date: '2024-07-15', total_amount: 4800, amount_paid: 1200, payment_plan: 'monthly', services_included: 'Double plot, burial services', status: 'active' },
      { contract_number: 'PN-2024-012', client_first_name: 'Brian', client_last_name: 'Turner', client_email: 'brian.t@email.com', client_phone: '555-0312', client_dob: '1957-10-08', contract_date: '2023-08-10', total_amount: 6000, amount_paid: 4000, payment_plan: 'monthly', services_included: 'Plot, mausoleum option, service', status: 'active' },
      { contract_number: 'PN-2024-013', client_first_name: 'Sandra', client_last_name: 'Hall', client_email: 'sandra.h@email.com', client_phone: '555-0313', client_dob: '1980-05-01', contract_date: '2024-08-01', total_amount: 2800, amount_paid: 700, payment_plan: 'quarterly', services_included: 'Cremation, columbarium niche', status: 'active' },
      { contract_number: 'PN-2024-014', client_first_name: 'Kenneth', client_last_name: 'Allen', client_email: 'ken.a@email.com', client_phone: '555-0314', client_dob: '1945-09-28', contract_date: '2022-03-15', total_amount: 8500, amount_paid: 8500, payment_plan: 'full', services_included: 'Family plot, multiple burials, monument', status: 'active' },
      { contract_number: 'PN-2024-015', client_first_name: 'Betty', client_last_name: 'Wright', client_email: 'betty.w@email.com', client_phone: '555-0315', client_dob: '1950-12-12', contract_date: '2024-09-01', total_amount: 4000, amount_paid: 1000, payment_plan: 'monthly', services_included: 'Plot, burial, flat marker', status: 'active' }
    ]);
    console.log('✓ Pre-Need Contracts seeded (15)');

    // 6. Monument Orders (15 records)
    await MonumentOrder.bulkCreate([
      { order_number: 'MO-2024-001', plot_id: 1, deceased_name: 'Robert Johnson', marker_type: 'veteran_marker', material: 'Granite - Gray', inscription: 'Robert E. Johnson\\nUS Navy\\nKorea\\n1935-2024', vendor: 'Heritage Monuments', order_date: '2024-01-20', expected_delivery: '2024-04-20', installation_date: '2024-05-01', cost: 1200, status: 'installed' },
      { order_number: 'MO-2024-002', plot_id: 2, deceased_name: 'Eleanor Williams', marker_type: 'headstone', material: 'Marble - White', inscription: 'Eleanor M. Williams\\nBeloved Mother & Teacher\\n1942-2024', vendor: 'Eternal Stone Works', order_date: '2024-02-15', expected_delivery: '2024-05-15', installation_date: '2024-06-01', cost: 3500, status: 'installed' },
      { order_number: 'MO-2024-003', plot_id: 5, deceased_name: 'Martinez Family', marker_type: 'monument', material: 'Granite - Black', inscription: 'Martinez\\nForever in Our Hearts', vendor: 'Heritage Monuments', order_date: '2024-04-01', expected_delivery: '2024-07-01', installation_date: '2024-07-15', cost: 8500, status: 'installed' },
      { order_number: 'MO-2024-004', plot_id: 8, deceased_name: 'Dorothy Chen', marker_type: 'flat_marker', material: 'Bronze', inscription: 'Dorothy L. Chen\\nArtist & Philanthropist\\n1938-2024', vendor: 'Pacific Markers', order_date: '2024-04-10', expected_delivery: '2024-06-10', installation_date: '2024-06-20', cost: 1800, status: 'installed' },
      { order_number: 'MO-2024-005', plot_id: 13, deceased_name: 'William Thompson', marker_type: 'veteran_marker', material: 'Granite - White', inscription: 'William H. Thompson\\nPFC US Army\\nWWII\\nPurple Heart\\n1930-2024', vendor: 'VA Headstones', order_date: '2024-05-25', expected_delivery: '2024-08-25', installation_date: '2024-09-10', cost: 0, status: 'installed', notes: 'VA provided headstone' },
      { order_number: 'MO-2024-006', plot_id: 16, deceased_name: 'Margaret O\'Brien', marker_type: 'headstone', material: 'Granite - Rose', inscription: 'Margaret A. O\'Brien\\nA Life of Service\\n1945-2024', vendor: 'Eternal Stone Works', order_date: '2024-06-10', expected_delivery: '2024-09-10', installation_date: '2024-09-25', cost: 4200, status: 'installed' },
      { order_number: 'MO-2024-007', plot_id: 17, deceased_name: 'George Anderson', marker_type: 'veteran_marker', material: 'Granite - Gray', inscription: 'George R. Anderson\\nSgt USMC\\nVietnam\\n1948-2024', vendor: 'VA Headstones', order_date: '2024-07-20', expected_delivery: '2024-10-20', installation_date: '2024-11-01', cost: 0, status: 'installed', notes: 'VA provided headstone' },
      { order_number: 'MO-2024-008', plot_id: 3, deceased_name: 'Davis-Wilson Family', marker_type: 'monument', material: 'Granite - Black', inscription: 'Davis ~ Wilson\\nTogether Forever', vendor: 'Heritage Monuments', order_date: '2024-09-15', expected_delivery: '2024-12-15', cost: 7500, status: 'in_production' },
      { order_number: 'MO-2024-009', plot_id: 10, deceased_name: 'Charles Brown', marker_type: 'bench', material: 'Granite - Sierra', inscription: 'Charles W. Brown\\nHe Loved the Land\\n1937-2024', vendor: 'Memorial Benches Inc', order_date: '2024-11-10', expected_delivery: '2025-02-10', cost: 5500, status: 'delivered' },
      { order_number: 'MO-2024-010', plot_id: 14, deceased_name: 'Garcia-Jackson', marker_type: 'monument', material: 'Marble - Gray', inscription: 'Garcia ~ Jackson\\nIn Loving Memory', vendor: 'Eternal Stone Works', order_date: '2024-12-01', expected_delivery: '2025-03-01', cost: 9200, status: 'in_production' },
      { order_number: 'MO-2024-011', deceased_name: 'John Smith', marker_type: 'headstone', material: 'Granite - Blue', inscription: 'John A. Smith\\nDevoted Father\\n1958-2026', vendor: 'Heritage Monuments', order_date: '2026-03-15', expected_delivery: '2026-06-15', cost: 3800, status: 'ordered' },
      { order_number: 'MO-2024-012', deceased_name: 'Anna Kowalski', marker_type: 'plaque', material: 'Bronze', inscription: 'Anna M. Kowalski\\nForever in Our Hearts\\n1965-2026', vendor: 'Pacific Markers', order_date: '2026-03-18', expected_delivery: '2026-05-18', cost: 1500, status: 'ordered' },
      { order_number: 'MO-2024-013', deceased_name: 'Samuel Green', marker_type: 'headstone', material: 'Granite - Gray', inscription: 'Samuel D. Green\\nBeloved Husband & Father\\n1950-2026', vendor: 'Eternal Stone Works', order_date: '2026-03-20', expected_delivery: '2026-06-20', cost: 4000, status: 'ordered' },
      { order_number: 'MO-2024-014', plot_id: 6, deceased_name: 'Elizabeth King', marker_type: 'flat_marker', material: 'Bronze', inscription: 'Elizabeth R. King\\n1944-2026', vendor: 'Pacific Markers', order_date: '2026-03-22', expected_delivery: '2026-05-22', cost: 1600, status: 'ordered' },
      { order_number: 'MO-2024-015', deceased_name: 'David Foster', marker_type: 'plaque', material: 'Bronze', inscription: 'David J. Foster\\nRest in Peace\\n1970-2026', vendor: 'Heritage Monuments', order_date: '2026-03-22', expected_delivery: '2026-05-22', cost: 1200, status: 'ordered' }
    ]);
    console.log('✓ Monument Orders seeded (15)');

    // 7. Perpetual Care Fund (15 records)
    await PerpetualCareFund.bulkCreate([
      { fund_name: 'Johnson Family Care Fund', account_number: 'PCF-001', plot_id: 1, contributor_name: 'Mary Johnson', contribution_amount: 500, contribution_date: '2020-06-01', current_balance: 562.50, interest_rate: 2.5, status: 'active' },
      { fund_name: 'Williams Perpetual Care', account_number: 'PCF-002', plot_id: 2, contributor_name: 'Thomas Williams', contribution_amount: 750, contribution_date: '2021-04-01', current_balance: 806.25, interest_rate: 2.5, status: 'active' },
      { fund_name: 'Martinez Family Fund', account_number: 'PCF-003', plot_id: 5, contributor_name: 'Rosa Martinez', contribution_amount: 2000, contribution_date: '2018-12-01', current_balance: 2315.00, interest_rate: 2.75, status: 'active' },
      { fund_name: 'Chen Memorial Fund', account_number: 'PCF-004', plot_id: 8, contributor_name: 'Michael Chen', contribution_amount: 1000, contribution_date: '2022-02-01', current_balance: 1075.00, interest_rate: 2.5, status: 'active' },
      { fund_name: 'Thompson Veterans Care', account_number: 'PCF-005', plot_id: 13, contributor_name: 'Susan Thompson', contribution_amount: 500, contribution_date: '2021-01-01', current_balance: 537.50, interest_rate: 2.5, status: 'active' },
      { fund_name: 'General Grounds Fund', account_number: 'PCF-006', contributor_name: 'Cemetery Association', contribution_amount: 25000, contribution_date: '2015-01-01', current_balance: 32500.00, interest_rate: 3.0, last_disbursement: '2024-12-01', disbursement_amount: 2400, status: 'active' },
      { fund_name: 'Veterans Section Fund', account_number: 'PCF-007', contributor_name: 'VFW Post 123', contribution_amount: 10000, contribution_date: '2018-05-01', current_balance: 12100.00, interest_rate: 2.75, last_disbursement: '2024-11-01', disbursement_amount: 800, status: 'active' },
      { fund_name: 'Garden of Angels Fund', account_number: 'PCF-008', contributor_name: 'Springfield Women\'s Club', contribution_amount: 5000, contribution_date: '2020-03-01', current_balance: 5625.00, interest_rate: 2.5, status: 'active' },
      { fund_name: 'O\'Brien Family Care', account_number: 'PCF-009', plot_id: 16, contributor_name: 'Patrick O\'Brien', contribution_amount: 750, contribution_date: '2021-08-01', current_balance: 806.25, interest_rate: 2.5, status: 'active' },
      { fund_name: 'Anderson Memorial', account_number: 'PCF-010', plot_id: 17, contributor_name: 'Linda Anderson', contribution_amount: 600, contribution_date: '2022-05-01', current_balance: 645.00, interest_rate: 2.5, status: 'active' },
      { fund_name: 'Brown Estate Fund', account_number: 'PCF-011', plot_id: 10, contributor_name: 'Nancy Brown Estate', contribution_amount: 5000, contribution_date: '2019-03-01', current_balance: 5787.50, interest_rate: 2.75, status: 'active' },
      { fund_name: 'Historic Section Fund', account_number: 'PCF-012', contributor_name: 'Historical Society', contribution_amount: 15000, contribution_date: '2010-01-01', current_balance: 21750.00, interest_rate: 2.75, last_disbursement: '2024-10-01', disbursement_amount: 1500, status: 'active' },
      { fund_name: 'Chapel Maintenance Fund', account_number: 'PCF-013', contributor_name: 'Springfield Churches Council', contribution_amount: 8000, contribution_date: '2017-06-01', current_balance: 9600.00, interest_rate: 2.5, last_disbursement: '2024-09-01', disbursement_amount: 1200, status: 'active' },
      { fund_name: 'Mausoleum Care Fund', account_number: 'PCF-014', contributor_name: 'Premium Estates LLC', contribution_amount: 20000, contribution_date: '2016-01-01', current_balance: 25500.00, interest_rate: 3.0, last_disbursement: '2024-12-01', disbursement_amount: 3000, status: 'active' },
      { fund_name: 'Columbarium Fund', account_number: 'PCF-015', contributor_name: 'Cremation Society', contribution_amount: 7500, contribution_date: '2019-07-01', current_balance: 8531.25, interest_rate: 2.5, status: 'active' }
    ]);
    console.log('✓ Perpetual Care Fund seeded (15)');

    // 8. Grounds Maintenance (15 records)
    await GroundsMaintenance.bulkCreate([
      { task_name: 'Spring Lawn Mowing - Section A', section: 'A', task_type: 'mowing', scheduled_date: '2026-04-01', assigned_to: 'Mike Rodriguez', priority: 'medium', estimated_hours: 4, cost: 200, status: 'scheduled' },
      { task_name: 'Tree Trimming - Main Entrance', section: 'Entrance', task_type: 'trimming', scheduled_date: '2026-04-05', assigned_to: 'Green Team Inc', priority: 'high', estimated_hours: 8, cost: 800, status: 'scheduled' },
      { task_name: 'Irrigation System Check', section: 'All', task_type: 'irrigation', scheduled_date: '2026-03-25', assigned_to: 'Tom Harris', priority: 'high', estimated_hours: 6, cost: 350, status: 'in_progress' },
      { task_name: 'Fertilizing - Veteran Section', section: 'V', task_type: 'fertilizing', scheduled_date: '2026-04-10', assigned_to: 'Mike Rodriguez', priority: 'medium', estimated_hours: 3, cost: 250, status: 'scheduled' },
      { task_name: 'Flower Bed Planting - Chapel', section: 'Chapel', task_type: 'planting', scheduled_date: '2026-04-15', assigned_to: 'Garden Staff', priority: 'medium', estimated_hours: 5, cost: 450, status: 'scheduled' },
      { task_name: 'Winter Storm Cleanup', section: 'All', task_type: 'general', scheduled_date: '2026-03-01', completed_date: '2026-03-03', assigned_to: 'Full Crew', priority: 'urgent', estimated_hours: 16, actual_hours: 20, cost: 2400, status: 'completed' },
      { task_name: 'Pest Control Treatment', section: 'B,C', task_type: 'pest_control', scheduled_date: '2026-04-20', assigned_to: 'ABC Pest Control', priority: 'medium', estimated_hours: 4, cost: 600, status: 'scheduled' },
      { task_name: 'Leaf Cleanup - Fall Season', section: 'All', task_type: 'leaf_cleanup', scheduled_date: '2025-11-01', completed_date: '2025-11-15', assigned_to: 'Full Crew', priority: 'medium', estimated_hours: 40, actual_hours: 45, cost: 3200, status: 'completed' },
      { task_name: 'Snow Removal - Paths', section: 'All', task_type: 'snow_removal', scheduled_date: '2026-01-15', completed_date: '2026-01-15', assigned_to: 'Maintenance Team', priority: 'urgent', estimated_hours: 8, actual_hours: 10, cost: 1500, status: 'completed' },
      { task_name: 'Mowing - Section D & E', section: 'D,E', task_type: 'mowing', scheduled_date: '2026-04-03', assigned_to: 'Mike Rodriguez', priority: 'medium', estimated_hours: 6, cost: 300, status: 'scheduled' },
      { task_name: 'Headstone Leveling - Section A', section: 'A', task_type: 'general', scheduled_date: '2026-04-08', assigned_to: 'Stone Crew', priority: 'low', estimated_hours: 8, cost: 1200, status: 'scheduled' },
      { task_name: 'Garden Renovation - Memorial Garden', section: 'Garden', task_type: 'planting', scheduled_date: '2026-05-01', assigned_to: 'Garden Staff', priority: 'medium', estimated_hours: 20, cost: 3500, status: 'scheduled' },
      { task_name: 'Road Repair - Section F Access', section: 'F', task_type: 'general', scheduled_date: '2026-04-25', assigned_to: 'Highway Contractors', priority: 'high', estimated_hours: 16, cost: 5000, status: 'scheduled' },
      { task_name: 'Fence Repair - North Boundary', section: 'Perimeter', task_type: 'general', scheduled_date: '2026-03-20', completed_date: '2026-03-22', assigned_to: 'Maintenance Team', priority: 'high', estimated_hours: 12, actual_hours: 14, cost: 2800, status: 'completed' },
      { task_name: 'Spring Planting - Columbarium Garden', section: 'Columbarium', task_type: 'planting', scheduled_date: '2026-04-12', assigned_to: 'Garden Staff', priority: 'medium', estimated_hours: 6, cost: 500, status: 'scheduled' }
    ]);
    console.log('✓ Grounds Maintenance seeded (15)');

    // 9. Flower Placements (15 records)
    await FlowerPlacement.bulkCreate([
      { plot_id: 1, deceased_name: 'Robert Johnson', placed_by: 'Mary Johnson', flower_type: 'Red Roses', arrangement_type: 'bouquet', placement_date: '2026-03-15', occasion: 'Birthday Remembrance', vendor: 'Springfield Florist', cost: 65, status: 'placed' },
      { plot_id: 2, deceased_name: 'Eleanor Williams', placed_by: 'Thomas Williams', flower_type: 'White Lilies', arrangement_type: 'spray', placement_date: '2026-03-10', occasion: 'Anniversary', vendor: 'Petal Perfect', cost: 95, status: 'placed' },
      { plot_id: 5, deceased_name: 'James Martinez', placed_by: 'Rosa Martinez', flower_type: 'Mixed Flowers', arrangement_type: 'standing', placement_date: '2026-03-18', occasion: 'Birthday', vendor: 'Rosa\'s Garden', cost: 120, status: 'placed' },
      { plot_id: 8, deceased_name: 'Dorothy Chen', placed_by: 'Michael Chen', flower_type: 'Chrysanthemums', arrangement_type: 'potted', placement_date: '2026-03-01', occasion: 'Monthly Visit', vendor: 'Springfield Florist', cost: 35, status: 'placed' },
      { plot_id: 13, deceased_name: 'William Thompson', placed_by: 'VFW Post 123', flower_type: 'Flag & Flowers', arrangement_type: 'wreath', placement_date: '2026-03-20', occasion: 'Veterans Remembrance', vendor: 'Patriot Flowers', cost: 85, status: 'placed' },
      { plot_id: 16, deceased_name: 'Margaret O\'Brien', placed_by: 'Patrick O\'Brien', flower_type: 'Pink Carnations', arrangement_type: 'bouquet', placement_date: '2026-03-12', occasion: 'Monthly Visit', vendor: 'Petal Perfect', cost: 45, status: 'placed' },
      { plot_id: 17, deceased_name: 'George Anderson', placed_by: 'Linda Anderson', flower_type: 'Sunflowers', arrangement_type: 'bouquet', placement_date: '2026-03-08', occasion: 'His Favorite', vendor: 'Springfield Florist', cost: 55, status: 'placed' },
      { plot_id: 1, deceased_name: 'Robert Johnson', placed_by: 'Grandchildren', flower_type: 'Daisies', arrangement_type: 'bouquet', placement_date: '2026-02-14', removal_date: '2026-02-28', occasion: 'Valentine\'s Day', vendor: 'Springfield Florist', cost: 40, status: 'removed' },
      { plot_id: 5, deceased_name: 'Helen Taylor', placed_by: 'Robert Taylor', flower_type: 'Purple Iris', arrangement_type: 'potted', placement_date: '2026-03-05', occasion: 'Spring Visit', vendor: 'Garden Gate', cost: 30, status: 'placed' },
      { plot_id: 10, deceased_name: 'Charles Brown', placed_by: 'Nancy Brown', flower_type: 'Wildflower Mix', arrangement_type: 'bouquet', placement_date: '2026-03-15', occasion: 'Spring Season', vendor: 'Country Flowers', cost: 50, status: 'placed' },
      { plot_id: 14, deceased_name: 'Barbara Garcia', placed_by: 'Carlos Garcia', flower_type: 'Red & White Roses', arrangement_type: 'spray', placement_date: '2026-03-20', occasion: 'Monthly Remembrance', vendor: 'Petal Perfect', cost: 110, status: 'placed' },
      { plot_id: 3, deceased_name: 'Patricia Davis', placed_by: 'John Davis', flower_type: 'Artificial Arrangement', arrangement_type: 'artificial', placement_date: '2026-01-15', occasion: 'Permanent Display', cost: 150, status: 'permanent' },
      { plot_id: 16, deceased_name: 'Margaret O\'Brien', placed_by: 'Nursing Staff', flower_type: 'Mixed Bouquet', arrangement_type: 'bouquet', placement_date: '2026-02-20', removal_date: '2026-03-05', occasion: 'In Her Memory', vendor: 'Springfield Florist', cost: 75, status: 'removed' },
      { plot_id: 17, deceased_name: 'George Anderson', placed_by: 'Fire Department', flower_type: 'Red Roses & White Lilies', arrangement_type: 'wreath', placement_date: '2026-03-01', occasion: 'Department Tribute', vendor: 'Patriot Flowers', cost: 200, status: 'placed' },
      { plot_id: 5, deceased_name: 'Frank Miller', placed_by: 'Sharon Miller', flower_type: 'Yellow Roses', arrangement_type: 'bouquet', placement_date: '2026-03-14', occasion: 'Anniversary', vendor: 'Springfield Florist', cost: 60, status: 'placed' }
    ]);
    console.log('✓ Flower Placements seeded (15)');

    // 10. Ceremony Schedules (15 records)
    await CeremonySchedule.bulkCreate([
      { event_name: 'Johnson Memorial Service', event_type: 'funeral', venue: 'main_chapel', scheduled_date: '2024-01-15', start_time: '09:00', end_time: '10:00', deceased_name: 'Robert Johnson', contact_name: 'Mary Johnson', contact_phone: '555-0101', expected_attendees: 75, officiant: 'Rev. Smith', status: 'completed' },
      { event_name: 'Williams Celebration of Life', event_type: 'celebration_of_life', venue: 'garden', scheduled_date: '2024-02-09', start_time: '13:00', end_time: '15:00', deceased_name: 'Eleanor Williams', contact_name: 'Thomas Williams', contact_phone: '555-0102', expected_attendees: 100, officiant: 'Rev. Johnson', status: 'completed' },
      { event_name: 'Martinez Funeral Mass', event_type: 'funeral', venue: 'main_chapel', scheduled_date: '2024-03-22', start_time: '10:00', end_time: '11:30', deceased_name: 'James Martinez', contact_name: 'Rosa Martinez', contact_phone: '555-0103', expected_attendees: 120, officiant: 'Father Rodriguez', status: 'completed' },
      { event_name: 'Chen Graveside Service', event_type: 'graveside', venue: 'graveside', scheduled_date: '2024-04-06', start_time: '09:00', end_time: '09:45', deceased_name: 'Dorothy Chen', contact_name: 'Michael Chen', contact_phone: '555-0104', expected_attendees: 50, officiant: 'Rev. Lee', status: 'completed' },
      { event_name: 'Thompson Military Honors', event_type: 'committal', venue: 'graveside', scheduled_date: '2024-05-19', start_time: '12:00', end_time: '13:00', deceased_name: 'William Thompson', contact_name: 'Susan Thompson', contact_phone: '555-0105', expected_attendees: 200, officiant: 'Military Chaplain', special_requirements: 'Honor guard, 21-gun salute, flag folding', status: 'completed' },
      { event_name: 'Smith Funeral Service', event_type: 'funeral', venue: 'main_chapel', scheduled_date: '2026-04-10', start_time: '09:00', end_time: '10:30', deceased_name: 'John Smith', contact_name: 'Jane Smith', contact_phone: '555-0401', expected_attendees: 60, officiant: 'Rev. Smith', status: 'scheduled' },
      { event_name: 'Kowalski Memorial', event_type: 'memorial', venue: 'small_chapel', scheduled_date: '2026-04-12', start_time: '13:00', end_time: '14:00', deceased_name: 'Anna Kowalski', contact_name: 'Peter Kowalski', contact_phone: '555-0402', expected_attendees: 30, officiant: 'Rev. Brown', status: 'scheduled' },
      { event_name: 'Green Celebration of Life', event_type: 'celebration_of_life', venue: 'reception_hall', scheduled_date: '2026-04-15', start_time: '14:00', end_time: '17:00', deceased_name: 'Samuel Green', contact_name: 'Ruth Green', contact_phone: '555-0403', expected_attendees: 90, officiant: 'Rabbi Cohen', status: 'confirmed' },
      { event_name: 'King Graveside Service', event_type: 'graveside', venue: 'graveside', scheduled_date: '2026-04-18', start_time: '08:30', end_time: '09:15', deceased_name: 'Elizabeth King', contact_name: 'James King', contact_phone: '555-0404', expected_attendees: 70, officiant: 'Rev. Williams', status: 'scheduled' },
      { event_name: 'Foster Committal Service', event_type: 'committal', venue: 'mausoleum', scheduled_date: '2026-04-20', start_time: '13:00', end_time: '13:45', deceased_name: 'David Foster', contact_name: 'Susan Foster', contact_phone: '555-0405', expected_attendees: 25, officiant: 'Rev. Adams', status: 'scheduled' },
      { event_name: 'Spring Memorial Day Event', event_type: 'memorial', venue: 'garden', scheduled_date: '2026-05-25', start_time: '10:00', end_time: '12:00', contact_name: 'Event Committee', contact_phone: '555-0406', expected_attendees: 300, officiant: 'Multiple', special_requirements: 'Sound system, chairs for 300, tent', status: 'confirmed' },
      { event_name: 'Gonzalez Funeral', event_type: 'funeral', venue: 'main_chapel', scheduled_date: '2026-04-25', start_time: '09:30', end_time: '11:00', deceased_name: 'Maria Gonzalez', contact_name: 'Pedro Gonzalez', contact_phone: '555-0407', expected_attendees: 110, officiant: 'Father Hernandez', status: 'scheduled' },
      { event_name: 'Wright Military Service', event_type: 'committal', venue: 'graveside', scheduled_date: '2026-05-01', start_time: '14:00', end_time: '15:00', deceased_name: 'Henry Wright', contact_name: 'Laura Wright', contact_phone: '555-0408', expected_attendees: 180, officiant: 'Military Chaplain', special_requirements: 'Full military honors', status: 'scheduled' },
      { event_name: 'Cooper Wake Service', event_type: 'wake', venue: 'reception_hall', scheduled_date: '2026-05-04', start_time: '17:00', end_time: '20:00', deceased_name: 'Jane Cooper', contact_name: 'Robert Cooper', contact_phone: '555-0409', expected_attendees: 45, status: 'scheduled' },
      { event_name: 'Cooper Funeral', event_type: 'funeral', venue: 'small_chapel', scheduled_date: '2026-05-05', start_time: '10:00', end_time: '11:30', deceased_name: 'Jane Cooper', contact_name: 'Robert Cooper', contact_phone: '555-0409', expected_attendees: 45, officiant: 'Rev. Thomas', status: 'scheduled' }
    ]);
    console.log('✓ Ceremony Schedules seeded (15)');

    // 11. Vendors (15 records)
    await Vendor.bulkCreate([
      { company_name: 'Peaceful Rest Funeral Home', vendor_type: 'other', contact_name: 'James Moore', email: 'james@peacefulrest.com', phone: '555-1001', address: '100 Main St, Springfield', license_number: 'FH-2024-001', insurance_expiry: '2027-01-01', contract_start: '2023-01-01', contract_end: '2026-12-31', rating: 5, status: 'active' },
      { company_name: 'Heritage Monuments', vendor_type: 'monument', contact_name: 'Steve Mason', email: 'steve@heritagemon.com', phone: '555-1002', address: '200 Stone Way, Springfield', license_number: 'MN-2024-001', insurance_expiry: '2026-06-01', contract_start: '2022-06-01', contract_end: '2026-05-31', rating: 5, status: 'active' },
      { company_name: 'Eternal Stone Works', vendor_type: 'monument', contact_name: 'Robert Stone', email: 'rob@eternalstone.com', phone: '555-1003', address: '300 Quarry Rd, Riverside', license_number: 'MN-2024-002', insurance_expiry: '2026-08-01', contract_start: '2023-08-01', contract_end: '2026-07-31', rating: 4, status: 'active' },
      { company_name: 'Springfield Florist', vendor_type: 'florist', contact_name: 'Maria Flores', email: 'maria@springfieldflorist.com', phone: '555-1004', address: '400 Garden Ave, Springfield', license_number: 'FL-2024-001', insurance_expiry: '2026-12-01', contract_start: '2024-01-01', contract_end: '2026-12-31', rating: 5, status: 'active' },
      { company_name: 'Petal Perfect', vendor_type: 'florist', contact_name: 'Laura Bloom', email: 'laura@petalperfect.com', phone: '555-1005', address: '500 Blossom St, Springfield', license_number: 'FL-2024-002', insurance_expiry: '2026-09-01', contract_start: '2023-09-01', contract_end: '2026-08-31', rating: 4, status: 'active' },
      { company_name: 'Secure Vaults Inc', vendor_type: 'vault', contact_name: 'Tom Vault', email: 'tom@securevaults.com', phone: '555-1006', address: '600 Industrial Blvd, Springfield', license_number: 'VT-2024-001', insurance_expiry: '2027-03-01', contract_start: '2024-03-01', contract_end: '2027-02-28', rating: 5, status: 'active' },
      { company_name: 'Pacific Markers', vendor_type: 'monument', contact_name: 'Ken Pacific', email: 'ken@pacificmarkers.com', phone: '555-1007', address: '700 Coast Hwy, Seaside', license_number: 'MN-2024-003', insurance_expiry: '2026-11-01', contract_start: '2023-11-01', contract_end: '2026-10-31', rating: 4, status: 'active' },
      { company_name: 'Green Lawns Landscaping', vendor_type: 'landscaping', contact_name: 'Mike Green', email: 'mike@greenlawns.com', phone: '555-1008', address: '800 Park Rd, Springfield', license_number: 'LS-2024-001', insurance_expiry: '2026-04-01', contract_start: '2024-04-01', contract_end: '2027-03-31', rating: 5, status: 'active' },
      { company_name: 'Memorial Benches Inc', vendor_type: 'monument', contact_name: 'Dave Bench', email: 'dave@memorialbenches.com', phone: '555-1009', address: '900 Craftsman Way, Springfield', license_number: 'MN-2024-004', insurance_expiry: '2026-07-01', contract_start: '2023-07-01', contract_end: '2026-06-30', rating: 4, status: 'active' },
      { company_name: 'Serenity Caskets', vendor_type: 'casket', contact_name: 'Sarah Peace', email: 'sarah@serenitycaskets.com', phone: '555-1010', address: '1000 Serenity Ln, Springfield', license_number: 'CS-2024-001', insurance_expiry: '2027-01-01', contract_start: '2024-01-01', contract_end: '2026-12-31', rating: 5, status: 'active' },
      { company_name: 'Eternal Urns', vendor_type: 'urn', contact_name: 'Grace Urn', email: 'grace@eternalurns.com', phone: '555-1011', address: '1100 Ceramic Blvd, Artisan City', license_number: 'UR-2024-001', insurance_expiry: '2026-10-01', contract_start: '2024-10-01', contract_end: '2027-09-30', rating: 4, status: 'active' },
      { company_name: 'Comfort Catering', vendor_type: 'catering', contact_name: 'Chef Marco', email: 'marco@comfortcatering.com', phone: '555-1012', address: '1200 Kitchen Way, Springfield', license_number: 'CT-2024-001', insurance_expiry: '2026-05-01', contract_start: '2023-05-01', contract_end: '2026-04-30', rating: 5, status: 'active' },
      { company_name: 'Dignified Transport', vendor_type: 'transportation', contact_name: 'Carl Driver', email: 'carl@dignifiedtrans.com', phone: '555-1013', address: '1300 Fleet St, Springfield', license_number: 'TR-2024-001', insurance_expiry: '2026-08-01', contract_start: '2024-08-01', contract_end: '2027-07-31', rating: 5, status: 'active' },
      { company_name: 'ABC Pest Control', vendor_type: 'other', contact_name: 'Art Bug', email: 'art@abcpest.com', phone: '555-1014', address: '1400 Bug Free Ave, Springfield', license_number: 'PC-2024-001', insurance_expiry: '2026-06-01', contract_start: '2023-06-01', contract_end: '2026-05-31', rating: 4, status: 'active' },
      { company_name: 'Patriot Flowers', vendor_type: 'florist', contact_name: 'Pat Flag', email: 'pat@patriotflowers.com', phone: '555-1015', address: '1500 Veterans Way, Springfield', license_number: 'FL-2024-003', insurance_expiry: '2027-01-01', contract_start: '2024-01-01', contract_end: '2026-12-31', rating: 5, status: 'active', notes: 'Specializes in veteran memorial arrangements' }
    ]);
    console.log('✓ Vendors seeded (15)');

    // 12. Compliance Records (15 records)
    await ComplianceRecord.bulkCreate([
      { regulation_name: 'Cemetery Operating License', regulation_type: 'state', description: 'Annual state operating license for cemetery operations', compliance_status: 'compliant', last_audit_date: '2025-12-01', next_audit_date: '2026-12-01', responsible_person: 'John Administrator', documentation_path: '/docs/licenses/operating_2026.pdf' },
      { regulation_name: 'Environmental Impact Assessment', regulation_type: 'environmental', description: 'Annual environmental assessment for groundwater and soil quality', compliance_status: 'compliant', last_audit_date: '2025-10-15', next_audit_date: '2026-10-15', responsible_person: 'Environmental Officer' },
      { regulation_name: 'OSHA Workplace Safety', regulation_type: 'osha', description: 'Workplace safety standards for maintenance and burial operations', compliance_status: 'compliant', last_audit_date: '2025-11-01', next_audit_date: '2026-05-01', responsible_person: 'Safety Director' },
      { regulation_name: 'Burial Depth Requirements', regulation_type: 'state', description: 'State regulation requiring minimum burial depth of 4 feet', compliance_status: 'compliant', last_audit_date: '2025-09-01', next_audit_date: '2026-09-01', responsible_person: 'Operations Manager' },
      { regulation_name: 'Embalming Fluid Disposal', regulation_type: 'environmental', description: 'Proper disposal of chemicals used in burial preparation', compliance_status: 'compliant', last_audit_date: '2025-08-15', next_audit_date: '2026-08-15', responsible_person: 'Environmental Officer' },
      { regulation_name: 'Consumer Protection - Pre-Need', regulation_type: 'state', description: 'State consumer protection laws for pre-need contracts', compliance_status: 'compliant', last_audit_date: '2025-07-01', next_audit_date: '2026-07-01', responsible_person: 'Legal Compliance', documentation_path: '/docs/compliance/preneed_audit_2025.pdf' },
      { regulation_name: 'Perpetual Care Fund Minimum', regulation_type: 'state', description: 'State required minimum perpetual care fund balance', compliance_status: 'compliant', last_audit_date: '2025-12-15', next_audit_date: '2026-06-15', responsible_person: 'Finance Director' },
      { regulation_name: 'ADA Accessibility', regulation_type: 'federal', description: 'Americans with Disabilities Act compliance for paths and facilities', compliance_status: 'pending_review', last_audit_date: '2025-06-01', next_audit_date: '2026-06-01', responsible_person: 'Facilities Manager', corrective_action: 'Review wheelchair accessibility of new columbarium section' },
      { regulation_name: 'Veterans Burial Benefits', regulation_type: 'federal', description: 'Compliance with VA burial benefit regulations', compliance_status: 'compliant', last_audit_date: '2025-11-15', next_audit_date: '2026-11-15', responsible_person: 'Veterans Liaison' },
      { regulation_name: 'Fire Safety - Chapel', regulation_type: 'local', description: 'Fire safety inspection for chapel and reception facilities', compliance_status: 'compliant', last_audit_date: '2026-01-15', next_audit_date: '2027-01-15', responsible_person: 'Facilities Manager' },
      { regulation_name: 'Groundwater Monitoring', regulation_type: 'environmental', description: 'Quarterly groundwater quality monitoring', compliance_status: 'compliant', last_audit_date: '2026-01-01', next_audit_date: '2026-04-01', responsible_person: 'Environmental Officer' },
      { regulation_name: 'Record Retention Policy', regulation_type: 'state', description: 'Permanent retention of burial records per state law', compliance_status: 'compliant', last_audit_date: '2025-05-01', next_audit_date: '2026-05-01', responsible_person: 'Records Manager' },
      { regulation_name: 'Cremation Standards', regulation_type: 'state', description: 'State standards for cremation procedures and record keeping', compliance_status: 'compliant', last_audit_date: '2025-10-01', next_audit_date: '2026-10-01', responsible_person: 'Cremation Director' },
      { regulation_name: 'Stormwater Management', regulation_type: 'environmental', description: 'EPA stormwater management compliance for cemetery grounds', compliance_status: 'under_remediation', last_audit_date: '2026-02-01', next_audit_date: '2026-08-01', responsible_person: 'Environmental Officer', corrective_action: 'Install additional drainage in Section F expansion area', fine_amount: 2500 },
      { regulation_name: 'Employee Background Checks', regulation_type: 'state', description: 'Required background checks for all cemetery employees', compliance_status: 'compliant', last_audit_date: '2026-01-01', next_audit_date: '2027-01-01', responsible_person: 'HR Director' }
    ]);
    console.log('✓ Compliance Records seeded (15)');

    // 13. Memorial Events (15 records)
    await MemorialEvent.bulkCreate([
      { event_name: 'Memorial Day Ceremony 2026', event_type: 'memorial_day', event_date: '2026-05-25', start_time: '10:00', end_time: '12:00', location: 'Veterans Memorial Plaza', organizer: 'VFW Post 123 & Cemetery Staff', expected_attendees: 500, budget: 5000, description: 'Annual Memorial Day ceremony with flag placement, music, and speakers', status: 'confirmed' },
      { event_name: 'Veterans Day Tribute 2026', event_type: 'veterans_day', event_date: '2026-11-11', start_time: '11:00', end_time: '13:00', location: 'Veterans Section', organizer: 'American Legion', expected_attendees: 300, budget: 3500, description: 'Veterans Day observance with 21-gun salute and wreath laying', status: 'planning' },
      { event_name: 'Easter Sunrise Service', event_type: 'holiday', event_date: '2026-04-05', start_time: '06:00', end_time: '07:30', location: 'Memorial Garden', organizer: 'Springfield Churches Council', expected_attendees: 200, budget: 1500, description: 'Interdenominational Easter sunrise service', status: 'confirmed' },
      { event_name: 'Historical Cemetery Tour', event_type: 'tour', event_date: '2026-04-18', start_time: '10:00', end_time: '12:00', location: 'Historic Section', organizer: 'Historical Society', expected_attendees: 50, budget: 500, description: 'Guided tour of historic graves and notable residents', status: 'confirmed' },
      { event_name: 'Spring Cleanup Volunteer Day', event_type: 'community', event_date: '2026-04-12', start_time: '08:00', end_time: '14:00', location: 'All Sections', organizer: 'Cemetery Staff & Rotary Club', expected_attendees: 100, budget: 800, description: 'Community volunteer day for spring cleanup and beautification', status: 'confirmed' },
      { event_name: 'Annual Fundraiser Gala', event_type: 'fundraiser', event_date: '2026-06-15', start_time: '18:00', end_time: '22:00', location: 'Springfield Grand Hotel', organizer: 'Cemetery Foundation', expected_attendees: 200, budget: 15000, description: 'Annual fundraiser for perpetual care fund and grounds improvements', status: 'planning' },
      { event_name: 'Independence Day Flag Ceremony', event_type: 'holiday', event_date: '2026-07-04', start_time: '09:00', end_time: '10:00', location: 'Veterans Section', organizer: 'Boy Scouts Troop 42', expected_attendees: 150, budget: 300, description: 'Flag placement on all veteran graves', status: 'planning' },
      { event_name: 'Dia de los Muertos Celebration', event_type: 'community', event_date: '2026-11-02', start_time: '16:00', end_time: '21:00', location: 'Garden & Chapel', organizer: 'Latino Community Association', expected_attendees: 250, budget: 2000, description: 'Day of the Dead celebration with altars, music, and food', status: 'planning' },
      { event_name: 'Christmas Luminary Walk', event_type: 'holiday', event_date: '2026-12-20', start_time: '17:00', end_time: '20:00', location: 'Main Paths', organizer: 'Cemetery Staff', expected_attendees: 400, budget: 2500, description: 'Evening luminary walk through decorated cemetery grounds', status: 'planning' },
      { event_name: 'Genealogy Workshop', event_type: 'community', event_date: '2026-04-22', start_time: '13:00', end_time: '16:00', location: 'Reception Hall', organizer: 'Genealogy Society', expected_attendees: 40, budget: 200, description: 'Workshop on researching family history using cemetery records', status: 'confirmed' },
      { event_name: 'Pet Memorial Garden Opening', event_type: 'community', event_date: '2026-05-10', start_time: '10:00', end_time: '12:00', location: 'New Pet Section', organizer: 'Cemetery Board', expected_attendees: 75, budget: 1000, description: 'Grand opening of new pet memorial garden section', status: 'planning' },
      { event_name: 'Summer Concert Series - Opening', event_type: 'community', event_date: '2026-06-20', start_time: '18:00', end_time: '20:00', location: 'Memorial Amphitheater', organizer: 'Springfield Arts Council', expected_attendees: 150, budget: 2000, description: 'First of four summer evening concerts in memorial amphitheater', status: 'planning' },
      { event_name: 'Gold Star Families Tribute', event_type: 'memorial_day', event_date: '2026-09-27', start_time: '14:00', end_time: '16:00', location: 'Veterans Memorial Plaza', organizer: 'Gold Star Families Association', expected_attendees: 80, budget: 1500, description: 'Annual tribute to families who lost loved ones in military service', status: 'planning' },
      { event_name: 'All Saints Day Service', event_type: 'holiday', event_date: '2026-11-01', start_time: '10:00', end_time: '11:30', location: 'Main Chapel', organizer: 'Catholic Diocese', expected_attendees: 120, budget: 500, description: 'All Saints Day remembrance mass', status: 'planning' },
      { event_name: 'Year-End Memorial Service', event_type: 'other', event_date: '2026-12-31', start_time: '15:00', end_time: '16:30', location: 'Main Chapel', organizer: 'Cemetery Staff', expected_attendees: 100, budget: 800, description: 'Annual service remembering all who passed during the year', status: 'planning' }
    ]);
    console.log('✓ Memorial Events seeded (15)');

    // 14. Genealogy Records (15 records)
    await GenealogyRecord.bulkCreate([
      { person_name: 'Robert E. Johnson', birth_date: '1935-03-15', death_date: '2024-01-10', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Edward Johnson', mother_name: 'Martha (née Brown) Johnson', spouse_name: 'Mary Ann Johnson', children: 'Thomas Johnson, Sarah Johnson-Lee, Michael Johnson', plot_id: 1, burial_record_id: 1, occupation: 'Navy Veteran, Mechanic', military_service: 'US Navy, 1953-1957, Korea' },
      { person_name: 'Eleanor M. Williams', birth_date: '1942-07-22', death_date: '2024-02-05', birth_place: 'Chicago, IL', death_place: 'Springfield, IL', father_name: 'Harold Williams', mother_name: 'Betty (née Smith) Williams', spouse_name: 'Thomas Williams Sr.', children: 'Thomas Williams Jr., Elizabeth Williams-Park', plot_id: 2, burial_record_id: 2, occupation: 'Teacher, Springfield Elementary' },
      { person_name: 'James R. Martinez', birth_date: '1950-11-30', death_date: '2024-03-18', birth_place: 'San Antonio, TX', death_place: 'Springfield, IL', father_name: 'Ricardo Martinez', mother_name: 'Elena (née Gonzalez) Martinez', spouse_name: 'Rosa Martinez', children: 'Carlos Martinez, Ana Martinez-Stone, Luis Martinez', plot_id: 5, burial_record_id: 3, occupation: 'Business Owner, Martinez Construction' },
      { person_name: 'Dorothy L. Chen', birth_date: '1938-05-14', death_date: '2024-04-02', birth_place: 'San Francisco, CA', death_place: 'Springfield, IL', father_name: 'Li Wei Chen', mother_name: 'Mei Lin (née Wang) Chen', spouse_name: 'James Chen (deceased)', children: 'Michael Chen, Lisa Chen-Park', plot_id: 8, burial_record_id: 4, occupation: 'Artist, Gallery Owner' },
      { person_name: 'William H. Thompson', birth_date: '1930-09-08', death_date: '2024-05-15', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Henry Thompson', mother_name: 'Alice (née Mitchell) Thompson', spouse_name: 'Susan Thompson', children: 'David Thompson, Patricia Thompson-Burns', plot_id: 13, burial_record_id: 5, occupation: 'WWII Veteran, Factory Worker', military_service: 'US Army, 1948-1952, WWII/Korea, Purple Heart' },
      { person_name: 'Margaret A. O\'Brien', birth_date: '1945-12-25', death_date: '2024-06-01', birth_place: 'Boston, MA', death_place: 'Springfield, IL', father_name: 'Sean O\'Brien Sr.', mother_name: 'Katherine (née Murphy) O\'Brien', spouse_name: 'Patrick O\'Brien', children: 'Sean O\'Brien Jr., Colleen O\'Brien-Davis', plot_id: 16, burial_record_id: 6, occupation: 'Army Nurse Corps', military_service: 'US Army Nurse Corps, 1967-1975' },
      { person_name: 'George R. Anderson', birth_date: '1948-02-17', death_date: '2024-07-12', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Robert Anderson', mother_name: 'Virginia (née Clark) Anderson', spouse_name: 'Linda Anderson', children: 'Mark Anderson, Amy Anderson-Foster', plot_id: 17, burial_record_id: 7, occupation: 'USMC Veteran, Firefighter', military_service: 'US Marines, 1966-1970, Vietnam' },
      { person_name: 'Patricia J. Davis', birth_date: '1955-08-03', death_date: '2024-08-20', birth_place: 'Nashville, TN', death_place: 'Springfield, IL', father_name: 'Joseph Davis', mother_name: 'Lorraine (née Taylor) Davis', spouse_name: 'John Davis', children: 'Rebecca Davis, Matthew Davis', plot_id: 3, burial_record_id: 8, occupation: 'Musician, Choir Director' },
      { person_name: 'Richard P. Wilson', birth_date: '1940-04-11', death_date: '2024-09-05', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Paul Wilson', mother_name: 'Edith (née Parker) Wilson', spouse_name: 'Karen Wilson', children: 'Steven Wilson, Jennifer Wilson-Adams', plot_id: 3, burial_record_id: 9, occupation: 'Civil Engineer, State DOT' },
      { person_name: 'Helen B. Taylor', birth_date: '1933-01-20', death_date: '2024-10-10', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Benjamin Taylor', mother_name: 'Grace (née Cooper) Taylor', spouse_name: 'Robert Taylor Sr. (deceased)', children: 'Robert Taylor Jr., Carol Taylor-White', plot_id: 5, burial_record_id: 10, occupation: 'Librarian, Springfield Public Library' },
      { person_name: 'Charles W. Brown', birth_date: '1937-06-28', death_date: '2024-11-01', birth_place: 'Peoria, IL', death_place: 'Springfield, IL', father_name: 'Walter Brown', mother_name: 'Frances (née Green) Brown', spouse_name: 'Nancy Brown', children: 'William Brown, Laura Brown-King', plot_id: 10, burial_record_id: 11, occupation: 'Air Force Veteran, Farmer', military_service: 'US Air Force, 1955-1959' },
      { person_name: 'Barbara A. Garcia', birth_date: '1960-10-05', death_date: '2024-11-20', birth_place: 'Los Angeles, CA', death_place: 'Springfield, IL', father_name: 'Antonio Garcia', mother_name: 'Maria (née Lopez) Garcia', spouse_name: 'Carlos Garcia', children: 'Sofia Garcia, Miguel Garcia', plot_id: 14, burial_record_id: 12, occupation: 'Physician, Community Health Center' },
      { person_name: 'Thomas R. White', birth_date: '1952-03-09', death_date: '2024-12-01', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Raymond White', mother_name: 'Dorothy (née Clark) White', spouse_name: 'Jennifer White', children: 'Andrew White, Christine White-Moore', plot_id: 5, burial_record_id: 13, occupation: 'Professor of History, State University' },
      { person_name: 'Ruth M. Jackson', birth_date: '1929-11-15', death_date: '2025-01-08', birth_place: 'Springfield, IL', death_place: 'Springfield, IL', father_name: 'Martin Jackson', mother_name: 'Violet (née Adams) Jackson', spouse_name: 'David Jackson Sr. (deceased)', children: 'David Jackson Jr., Ruth Ann Jackson-Phillips, Grace Jackson', plot_id: 14, burial_record_id: 14, occupation: 'Homemaker, Church Elder' },
      { person_name: 'Frank S. Miller', birth_date: '1946-07-04', death_date: '2025-02-14', birth_place: 'Decatur, IL', death_place: 'Springfield, IL', father_name: 'Samuel Miller', mother_name: 'Ruth (née Harris) Miller', spouse_name: 'Sharon Miller', children: 'Frank Miller Jr., Diane Miller-Scott', plot_id: 5, burial_record_id: 15, occupation: 'Army Veteran, Community Volunteer', military_service: 'US Army, 1964-1968, Vietnam' }
    ]);
    console.log('✓ Genealogy Records seeded (15)');

    // 15. Payment Plans (15 records)
    await PaymentPlan.bulkCreate([
      { plan_number: 'PP-2024-001', client_name: 'David Lee', client_email: 'david.l@email.com', client_phone: '555-0501', deed_id: 6, total_amount: 6500, down_payment: 1000, monthly_payment: 229.17, total_paid: 3250, remaining_balance: 3250, start_date: '2023-06-01', end_date: '2025-06-01', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-002', client_name: 'Jennifer White', client_email: 'jen.w@email.com', client_phone: '555-0502', deed_id: 12, total_amount: 4500, down_payment: 500, monthly_payment: 333.33, total_paid: 1500, remaining_balance: 3000, start_date: '2024-01-10', end_date: '2025-01-10', payment_frequency: 'quarterly', status: 'active' },
      { plan_number: 'PP-2024-003', client_name: 'Robert Taylor', client_email: 'rob.t@email.com', client_phone: '555-0503', deed_id: 13, total_amount: 3800, down_payment: 800, monthly_payment: 125.00, total_paid: 950, remaining_balance: 2850, start_date: '2024-02-01', end_date: '2026-02-01', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-004', client_name: 'Sharon Miller', client_email: 'sharon.m@email.com', client_phone: '555-0504', deed_id: 14, total_amount: 5200, down_payment: 1200, monthly_payment: 200.00, total_paid: 2600, remaining_balance: 2600, start_date: '2023-11-20', end_date: '2025-07-20', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-005', client_name: 'Karen Wilson', client_email: 'karen.w@email.com', client_phone: '555-0505', deed_id: 15, total_amount: 5800, down_payment: 800, monthly_payment: 416.67, total_paid: 1450, remaining_balance: 4350, start_date: '2024-03-05', end_date: '2025-03-05', payment_frequency: 'quarterly', status: 'active' },
      { plan_number: 'PP-2024-006', client_name: 'Lisa Rogers', client_email: 'lisa.r@email.com', client_phone: '555-0506', total_amount: 3500, down_payment: 500, monthly_payment: 125.00, total_paid: 875, remaining_balance: 2625, start_date: '2024-05-10', end_date: '2026-05-10', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-007', client_name: 'Steven Clark', client_email: 'steve.c@email.com', client_phone: '555-0507', total_amount: 7200, down_payment: 1200, monthly_payment: 250.00, total_paid: 5400, remaining_balance: 1800, start_date: '2022-09-01', end_date: '2025-03-01', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-008', client_name: 'Angela Hill', client_email: 'angela.h@email.com', client_phone: '555-0508', total_amount: 3200, down_payment: 400, monthly_payment: 233.33, total_paid: 800, remaining_balance: 2400, start_date: '2024-06-01', end_date: '2025-06-01', payment_frequency: 'quarterly', status: 'active' },
      { plan_number: 'PP-2024-009', client_name: 'Dorothy Scott', client_email: 'dorothy.s@email.com', client_phone: '555-0509', total_amount: 4800, down_payment: 800, monthly_payment: 166.67, total_paid: 1200, remaining_balance: 3600, start_date: '2024-07-15', end_date: '2026-07-15', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-010', client_name: 'Brian Turner', client_email: 'brian.t@email.com', client_phone: '555-0510', total_amount: 6000, down_payment: 1000, monthly_payment: 208.33, total_paid: 4000, remaining_balance: 2000, start_date: '2023-08-10', end_date: '2025-08-10', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-011', client_name: 'Sandra Hall', client_email: 'sandra.h@email.com', client_phone: '555-0511', total_amount: 2800, down_payment: 300, monthly_payment: 208.33, total_paid: 700, remaining_balance: 2100, start_date: '2024-08-01', end_date: '2025-08-01', payment_frequency: 'quarterly', status: 'active' },
      { plan_number: 'PP-2024-012', client_name: 'Betty Wright', client_email: 'betty.w@email.com', client_phone: '555-0512', total_amount: 4000, down_payment: 500, monthly_payment: 145.83, total_paid: 1000, remaining_balance: 3000, start_date: '2024-09-01', end_date: '2026-09-01', payment_frequency: 'monthly', status: 'active' },
      { plan_number: 'PP-2024-013', client_name: 'Mary Johnson', client_email: 'mary.j@email.com', client_phone: '555-0201', deed_id: 1, total_amount: 2500, down_payment: 2500, monthly_payment: 0, total_paid: 2500, remaining_balance: 0, start_date: '2020-05-15', end_date: '2020-05-15', payment_frequency: 'monthly', status: 'paid_off' },
      { plan_number: 'PP-2024-014', client_name: 'Rosa Martinez', client_email: 'rosa.m@email.com', client_phone: '555-0203', deed_id: 5, total_amount: 8000, down_payment: 2000, monthly_payment: 500.00, total_paid: 8000, remaining_balance: 0, start_date: '2018-11-15', end_date: '2019-11-15', payment_frequency: 'monthly', status: 'paid_off' },
      { plan_number: 'PP-2024-015', client_name: 'Thomas Williams', client_email: 'tom.w@email.com', client_phone: '555-0202', deed_id: 2, total_amount: 2500, down_payment: 500, monthly_payment: 166.67, total_paid: 2500, remaining_balance: 0, start_date: '2021-03-20', end_date: '2022-03-20', payment_frequency: 'monthly', status: 'paid_off' }
    ]);
    console.log('✓ Payment Plans seeded (15)');

    // 16. Cremation Niches (15 records)
    await CremationNiche.bulkCreate([
      { niche_number: 'CN-A-1-01', columbarium_name: 'Serenity Columbarium', level: 'A', position: '1', size: 'single', status: 'occupied', occupant_name: 'Thomas Reed', date_of_inurnment: '2024-03-15', urn_type: 'Bronze', price: 1500, owner_name: 'Sandra Reed', owner_phone: '555-0601' },
      { niche_number: 'CN-A-1-02', columbarium_name: 'Serenity Columbarium', level: 'A', position: '2', size: 'single', status: 'occupied', occupant_name: 'Helen Parker', date_of_inurnment: '2024-05-20', urn_type: 'Marble', price: 1500, owner_name: 'James Parker', owner_phone: '555-0602' },
      { niche_number: 'CN-A-2-01', columbarium_name: 'Serenity Columbarium', level: 'A', position: '3', size: 'double', status: 'occupied', occupant_name: 'George & Betty Foster', date_of_inurnment: '2024-07-10', urn_type: 'Companion Bronze', price: 2800, owner_name: 'Mark Foster', owner_phone: '555-0603' },
      { niche_number: 'CN-B-1-01', columbarium_name: 'Serenity Columbarium', level: 'B', position: '1', size: 'single', status: 'sold', price: 1600, owner_name: 'Lisa Rogers', owner_phone: '555-0604' },
      { niche_number: 'CN-B-1-02', columbarium_name: 'Serenity Columbarium', level: 'B', position: '2', size: 'single', status: 'available', price: 1600 },
      { niche_number: 'CN-B-2-01', columbarium_name: 'Serenity Columbarium', level: 'B', position: '3', size: 'double', status: 'available', price: 2900 },
      { niche_number: 'CN-C-1-01', columbarium_name: 'Peace Garden Columbarium', level: 'C', position: '1', size: 'single', status: 'occupied', occupant_name: 'Alice Morgan', date_of_inurnment: '2024-09-05', urn_type: 'Ceramic', price: 1200, owner_name: 'Robert Morgan', owner_phone: '555-0605' },
      { niche_number: 'CN-C-1-02', columbarium_name: 'Peace Garden Columbarium', level: 'C', position: '2', size: 'single', status: 'reserved', price: 1200, owner_name: 'Sandra Hall', owner_phone: '555-0606' },
      { niche_number: 'CN-C-2-01', columbarium_name: 'Peace Garden Columbarium', level: 'C', position: '3', size: 'family', status: 'sold', price: 4500, owner_name: 'Kenneth Allen', owner_phone: '555-0607' },
      { niche_number: 'CN-D-1-01', columbarium_name: 'Peace Garden Columbarium', level: 'D', position: '1', size: 'single', status: 'available', price: 1100 },
      { niche_number: 'CN-D-1-02', columbarium_name: 'Peace Garden Columbarium', level: 'D', position: '2', size: 'single', status: 'available', price: 1100 },
      { niche_number: 'CN-D-2-01', columbarium_name: 'Peace Garden Columbarium', level: 'D', position: '3', size: 'double', status: 'available', price: 2000 },
      { niche_number: 'CN-E-1-01', columbarium_name: 'Sunrise Columbarium', level: 'E', position: '1', size: 'single', status: 'occupied', occupant_name: 'Frank Stevens', date_of_inurnment: '2025-01-20', urn_type: 'Glass', price: 1800, owner_name: 'Emily Stevens', owner_phone: '555-0608' },
      { niche_number: 'CN-E-1-02', columbarium_name: 'Sunrise Columbarium', level: 'E', position: '2', size: 'single', status: 'available', price: 1800 },
      { niche_number: 'CN-E-2-01', columbarium_name: 'Sunrise Columbarium', level: 'E', position: '3', size: 'double', status: 'sold', price: 3200, owner_name: 'Dorothy Scott', owner_phone: '555-0609' }
    ]);
    console.log('✓ Cremation Niches seeded (15)');

    // 17. Veteran Records (15 records)
    await VeteranRecord.bulkCreate([
      { veteran_name: 'Robert E. Johnson', service_number: 'USN-55-12345', branch: 'navy', rank: 'Petty Officer 2nd Class', war_conflict: 'Korean War', enlistment_date: '1953-06-15', discharge_date: '1957-06-14', discharge_type: 'Honorable', date_of_birth: '1935-03-15', date_of_death: '2024-01-10', plot_id: 1, va_claim_number: 'VA-2024-001', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'William H. Thompson', service_number: 'USA-48-67890', branch: 'army', rank: 'Private First Class', war_conflict: 'World War II / Korea', enlistment_date: '1948-03-01', discharge_date: '1952-02-28', discharge_type: 'Honorable', date_of_birth: '1930-09-08', date_of_death: '2024-05-15', plot_id: 13, va_claim_number: 'VA-2024-002', headstone_type: 'Government Issue', flag_holder: true, notes: 'Purple Heart recipient' },
      { veteran_name: 'Margaret A. O\'Brien', service_number: 'USA-67-11111', branch: 'army', rank: 'Captain', war_conflict: 'Vietnam War', enlistment_date: '1967-01-15', discharge_date: '1975-01-14', discharge_type: 'Honorable', date_of_birth: '1945-12-25', date_of_death: '2024-06-01', plot_id: 16, va_claim_number: 'VA-2024-003', headstone_type: 'Private - Granite', flag_holder: true, notes: 'Army Nurse Corps' },
      { veteran_name: 'George R. Anderson', service_number: 'USMC-66-22222', branch: 'marines', rank: 'Sergeant', war_conflict: 'Vietnam War', enlistment_date: '1966-08-01', discharge_date: '1970-07-31', discharge_type: 'Honorable', date_of_birth: '1948-02-17', date_of_death: '2024-07-12', plot_id: 17, va_claim_number: 'VA-2024-004', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'Charles W. Brown', service_number: 'USAF-55-33333', branch: 'air_force', rank: 'Staff Sergeant', war_conflict: 'Cold War', enlistment_date: '1955-09-01', discharge_date: '1959-08-31', discharge_type: 'Honorable', date_of_birth: '1937-06-28', date_of_death: '2024-11-01', plot_id: 10, va_claim_number: 'VA-2024-005', headstone_type: 'Private - Bench', flag_holder: true },
      { veteran_name: 'Frank S. Miller', service_number: 'USA-64-44444', branch: 'army', rank: 'Specialist 4', war_conflict: 'Vietnam War', enlistment_date: '1964-11-01', discharge_date: '1968-10-31', discharge_type: 'Honorable', date_of_birth: '1946-07-04', date_of_death: '2025-02-14', plot_id: 5, va_claim_number: 'VA-2025-001', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'Henry P. Wright', service_number: 'USA-68-55555', branch: 'army', rank: 'Corporal', war_conflict: 'Vietnam War', enlistment_date: '1968-03-15', discharge_date: '1971-03-14', discharge_type: 'Honorable', date_of_birth: '1949-08-22', date_of_death: '2026-04-28', plot_id: 18, va_claim_number: 'VA-2026-001', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'Edward J. Collins', service_number: 'USN-62-66666', branch: 'navy', rank: 'Chief Petty Officer', war_conflict: 'Vietnam War', enlistment_date: '1962-05-01', discharge_date: '1982-04-30', discharge_type: 'Honorable', date_of_birth: '1944-01-10', date_of_death: '2023-12-20', plot_id: 16, va_claim_number: 'VA-2023-001', headstone_type: 'Government Issue', flag_holder: true, notes: '20-year career Navy' },
      { veteran_name: 'Arthur L. Brooks', service_number: 'USMC-50-77777', branch: 'marines', rank: 'Master Sergeant', war_conflict: 'Korean War', enlistment_date: '1950-07-01', discharge_date: '1970-06-30', discharge_type: 'Honorable', date_of_birth: '1932-05-15', date_of_death: '2023-08-10', plot_id: 17, va_claim_number: 'VA-2023-002', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'James T. Rivera', service_number: 'USA-03-88888', branch: 'army', rank: 'First Lieutenant', war_conflict: 'Iraq War', enlistment_date: '2003-06-01', discharge_date: '2007-05-31', discharge_type: 'Honorable', date_of_birth: '1981-11-25', date_of_death: '2023-06-15', plot_id: 16, va_claim_number: 'VA-2023-003', headstone_type: 'Government Issue', flag_holder: true, notes: 'Bronze Star recipient' },
      { veteran_name: 'Samuel K. Washington', service_number: 'USA-91-99999', branch: 'army', rank: 'Sergeant First Class', war_conflict: 'Gulf War / Afghanistan', enlistment_date: '1991-01-15', discharge_date: '2011-01-14', discharge_type: 'Honorable', date_of_birth: '1972-04-30', date_of_death: '2024-03-01', plot_id: 17, va_claim_number: 'VA-2024-006', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'Dorothy M. Hayes', service_number: 'USAF-80-10101', branch: 'air_force', rank: 'Technical Sergeant', war_conflict: 'Cold War / Gulf War', enlistment_date: '1980-06-01', discharge_date: '2000-05-31', discharge_type: 'Honorable', date_of_birth: '1962-09-12', date_of_death: '2024-08-15', plot_id: 16, va_claim_number: 'VA-2024-007', headstone_type: 'Private - Flat Marker', flag_holder: true },
      { veteran_name: 'Richard N. Foster', service_number: 'USCG-75-20202', branch: 'coast_guard', rank: 'Boatswain Mate 1st Class', war_conflict: 'Cold War', enlistment_date: '1975-09-01', discharge_date: '1995-08-31', discharge_type: 'Honorable', date_of_birth: '1957-12-03', date_of_death: '2024-10-22', plot_id: 17, va_claim_number: 'VA-2024-008', headstone_type: 'Government Issue', flag_holder: true },
      { veteran_name: 'Michael P. Torres', service_number: 'USA-10-30303', branch: 'army', rank: 'Captain', war_conflict: 'Afghanistan', enlistment_date: '2010-05-15', discharge_date: '2018-05-14', discharge_type: 'Honorable', date_of_birth: '1988-07-20', date_of_death: '2025-01-05', plot_id: 18, va_claim_number: 'VA-2025-002', headstone_type: 'Government Issue', flag_holder: true, notes: 'Silver Star recipient' },
      { veteran_name: 'Paul D. Newman', service_number: 'USNG-85-40404', branch: 'national_guard', rank: 'Staff Sergeant', war_conflict: 'Gulf War', enlistment_date: '1985-03-01', discharge_date: '2005-02-28', discharge_type: 'Honorable', date_of_birth: '1966-10-18', date_of_death: '2025-03-10', plot_id: 18, va_claim_number: 'VA-2025-003', headstone_type: 'Government Issue', flag_holder: true }
    ]);
    console.log('✓ Veteran Records seeded (15)');

    // 18. Deed Transfers (15 records)
    await DeedTransfer.bulkCreate([
      { deed_id: 1, transfer_number: 'DT-2024-001', from_owner: 'Robert Johnson', to_owner: 'Mary Johnson', transfer_date: '2020-05-15', transfer_type: 'inheritance', transfer_fee: 50, status: 'completed', notes: 'Transfer upon death of original deed holder' },
      { deed_id: 3, transfer_number: 'DT-2024-002', from_owner: 'James Martinez', to_owner: 'Rosa Martinez', transfer_date: '2019-08-10', transfer_type: 'gift', transfer_fee: 50, status: 'completed' },
      { deed_id: 5, transfer_number: 'DT-2024-003', from_owner: 'Martinez Family Trust', to_owner: 'Rosa Martinez', transfer_date: '2018-11-15', transfer_type: 'inheritance', transfer_fee: 0, status: 'completed', notes: 'Trust transfer' },
      { deed_id: 7, transfer_number: 'DT-2024-004', from_owner: 'Susan Thompson', to_owner: 'David Thompson', to_owner_email: 'david.t@email.com', to_owner_phone: '555-0701', transfer_date: '2026-03-01', transfer_type: 'inheritance', transfer_fee: 75, status: 'pending', notes: 'Transfer pending probate' },
      { deed_id: 8, transfer_number: 'DT-2024-005', from_owner: 'VA', to_owner: 'Patrick O\'Brien', transfer_date: '2021-07-15', transfer_type: 'gift', transfer_fee: 0, status: 'completed', notes: 'VA burial benefit' },
      { deed_id: 9, transfer_number: 'DT-2024-006', from_owner: 'VA', to_owner: 'Linda Anderson', transfer_date: '2022-04-10', transfer_type: 'gift', transfer_fee: 0, status: 'completed', notes: 'VA burial benefit' },
      { deed_id: 10, transfer_number: 'DT-2024-007', from_owner: 'Charles Brown', to_owner: 'Nancy Brown', transfer_date: '2019-02-28', transfer_type: 'sale', transfer_fee: 100, status: 'completed' },
      { deed_id: 11, transfer_number: 'DT-2024-008', from_owner: 'Carlos Garcia', to_owner: 'Sofia Garcia', to_owner_email: 'sofia.g@email.com', to_owner_phone: '555-0702', transfer_date: '2026-03-15', transfer_type: 'gift', transfer_fee: 50, status: 'pending' },
      { deed_id: 14, transfer_number: 'DT-2024-009', from_owner: 'Sharon Miller', to_owner: 'Frank Miller Jr.', to_owner_email: 'frank.jr@email.com', to_owner_phone: '555-0703', transfer_date: '2026-03-10', transfer_type: 'inheritance', transfer_fee: 75, status: 'pending', notes: 'Transfer pending probate' },
      { deed_id: 12, transfer_number: 'DT-2024-010', from_owner: 'Original Owner', to_owner: 'Jennifer White', transfer_date: '2024-01-10', transfer_type: 'sale', transfer_fee: 150, status: 'completed' },
      { deed_id: 13, transfer_number: 'DT-2024-011', from_owner: 'Previous Owner', to_owner: 'Robert Taylor', transfer_date: '2024-02-01', transfer_type: 'sale', transfer_fee: 100, status: 'completed' },
      { deed_id: 15, transfer_number: 'DT-2024-012', from_owner: 'Estate Sale', to_owner: 'Karen Wilson', transfer_date: '2024-03-05', transfer_type: 'court_order', transfer_fee: 200, legal_document: 'Court Order #2024-CV-1234', status: 'completed' },
      { deed_id: 2, transfer_number: 'DT-2024-013', from_owner: 'Eleanor Williams Estate', to_owner: 'Thomas Williams', transfer_date: '2024-02-20', transfer_type: 'inheritance', transfer_fee: 50, status: 'completed' },
      { deed_id: 4, transfer_number: 'DT-2024-014', from_owner: 'Michael Chen', to_owner: 'Lisa Chen-Park', to_owner_email: 'lisa.cp@email.com', to_owner_phone: '555-0704', transfer_date: '2026-02-15', transfer_type: 'gift', transfer_fee: 50, status: 'approved', notes: 'Transferring to daughter' },
      { deed_id: 6, transfer_number: 'DT-2024-015', from_owner: 'David Lee', to_owner: 'Sarah Lee', to_owner_email: 'sarah.l@email.com', to_owner_phone: '555-0705', transfer_date: '2026-03-20', transfer_type: 'gift', transfer_fee: 50, status: 'pending' }
    ]);
    console.log('✓ Deed Transfers seeded (15)');

    console.log('\n✅ All seed data inserted successfully!');
    console.log('📊 Summary:');
    console.log('   • Users: 2');
    console.log('   • Plots: 20');
    console.log('   • Burial Records: 15');
    console.log('   • Deeds: 15');
    console.log('   • Interment Schedules: 15');
    console.log('   • Pre-Need Contracts: 15');
    console.log('   • Monument Orders: 15');
    console.log('   • Perpetual Care Funds: 15');
    console.log('   • Grounds Maintenance: 15');
    console.log('   • Flower Placements: 15');
    console.log('   • Ceremony Schedules: 15');
    console.log('   • Vendors: 15');
    console.log('   • Compliance Records: 15');
    console.log('   • Memorial Events: 15');
    console.log('   • Genealogy Records: 15');
    console.log('   • Payment Plans: 15');
    console.log('   • Cremation Niches: 15');
    console.log('   • Veteran Records: 15');
    console.log('   • Deed Transfers: 15');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seed();
